import { useState } from 'react'
import { useNavigate } from 'react-router-dom'

export default function Home() {
  const [topic, setTopic] = useState('')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState(null)
  const navigate = useNavigate()

  const handleGenerate = async (e) => {
    e.preventDefault()
    if (!topic.trim()) return

    setLoading(true)
    setError(null)

    try {
      const resp = await fetch('/api/quiz/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ topic: topic.trim() }),
      })

      if (!resp.ok) {
        const data = await resp.json()
        throw new Error(data.detail || 'Failed to generate quiz')
      }

      const quiz = await resp.json()
      navigate(`/quiz/${quiz.id}`)
    } catch (err) {
      setError(err.message)
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="home">
      <div className="hero">
        <h1>AI-Powered Knowledge Quiz</h1>
        <p className="subtitle">
          Enter any topic and get a 5-question multiple-choice quiz generated by AI.
        </p>
      </div>

      <form onSubmit={handleGenerate} className="generate-form">
        <div className="input-group">
          <input
            type="text"
            value={topic}
            onChange={(e) => setTopic(e.target.value)}
            placeholder='Try "Photosynthesis", "Neural Networks", or "Ancient Rome"'
            className="topic-input"
            disabled={loading}
            autoFocus
          />
          <button
            type="submit"
            className="btn btn-primary"
            disabled={loading || !topic.trim()}
          >
            {loading ? 'Generating...' : 'Generate Quiz'}
          </button>
        </div>
        {error && <p className="error-message">{error}</p>}
      </form>

      {loading && (
        <div className="loading-state">
          <div className="spinner" />
          <p>Generating your quiz with AI... This may take a few seconds.</p>
        </div>
      )}
    </div>
  )
}
